services:
  - type: web
    name: jcc-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://jcc-inmobiliaria-app.onrender.com/api
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate 