databases:
  - name: jcc-postgres-db
    databaseName: jccinmobiliaria_db
    user: jcc_user
    plan: free

services:
  - type: web
    name: jcc-gestion-inmobiliaria
    env: python
    plan: free
    rootDir: jcc_inmobiliaria_backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    postdeploy:
      - echo "=== INICIANDO POSTDEPLOY ==="
      - python manage.py migrate --noinput
      - python manage.py shell < importar_clientes_temp.py
      - python manage.py shell < importar_lotes_temp.py
      - python manage.py shell < importar_asesores_temp.py
      - echo "=== POSTDEPLOY FINALIZADO ==="
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: jcc-inmobiliaria-app.onrender.com,jcc-gestion-inmobiliaria.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: jcc-postgres-db
          property: connectionString
      - key: CRM_WEBHOOK_TOKEN
        value: jcc-webhook-secret-token-2024
      - key: CORS_ALLOWED_ORIGINS
        value: https://jcc-frontend.onrender.com,http://localhost:5173
      - key: CSRF_TRUSTED_ORIGINS
        value: https://jcc-frontend.onrender.com,http://localhost:5173

  - type: web
    name: jcc-frontend
    env: static
    plan: free
    rootDir: jcc_inmobiliaria_frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://jcc-inmobiliaria-app.onrender.com/api 