# Generated by Django 5.2.1 on 2025-05-17 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Cliente')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de Extranjería'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], max_length=15, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('nombres_completos_razon_social', models.CharField(max_length=255, verbose_name='Nombres Completos / Razón Social')),
                ('fecha_nacimiento_constitucion', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento/Constitución')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_principal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Secundario')),
                ('email_principal', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Principal')),
                ('email_secundario', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Secundario')),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Conviviente', 'Conviviente')], max_length=20, null=True, verbose_name='Estado Civil')),
                ('profesion_ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesión/Ocupación')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombres_completos_razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ConfigGeneral',
            fields=[
                ('parametro', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Parámetro')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuraciones Generales',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoriaCambio',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('usuario_email', models.CharField(max_length=255, verbose_name='Usuario Email')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo Afectado')),
                ('id_registro_afectado', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Registro Afectado')),
                ('campo_modificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo Modificado')),
                ('valor_antiguo', models.TextField(blank=True, null=True, verbose_name='Valor Antiguo')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('detalles_adicionales', models.TextField(blank=True, null=True, verbose_name='Detalles Adicionales')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Lote')),
                ('ubicacion_proyecto', models.CharField(max_length=255, verbose_name='Ubicación del Proyecto')),
                ('manzana', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manzana')),
                ('numero_lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Lote')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('precio_lista_soles', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Lista (S/.)')),
                ('precio_lista_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Lista ($)')),
                ('estado_lote', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Vendido', 'Vendido')], default='Disponible', max_length=20, verbose_name='Estado del Lote')),
                ('colindancias', models.TextField(blank=True, null=True, verbose_name='Colindancias')),
                ('partida_registral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Partida Registral')),
                ('observaciones_lote', models.TextField(blank=True, null=True, verbose_name='Observaciones del Lote')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['id_lote'],
            },
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id_asesor', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Asesor')),
                ('nombre_asesor', models.CharField(max_length=255, verbose_name='Nombre del Asesor')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('tipo_asesor_actual', models.CharField(choices=[('Junior', 'Junior'), ('Socio', 'Socio')], max_length=10, verbose_name='Tipo Asesor Actual')),
                ('fecha_cambio_socio', models.DateField(blank=True, null=True, verbose_name='Fecha Cambio a Socio')),
                ('id_referidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='gestion_inmobiliaria.asesor', verbose_name='ID Referidor')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'ordering': ['nombre_asesor'],
            },
        ),
        migrations.CreateModel(
            name='DefinicionMetaComision',
            fields=[
                ('id_definicion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_asesor', models.CharField(choices=[('Junior', 'Junior'), ('Socio', 'Socio')], max_length=10, verbose_name='Tipo de Asesor')),
                ('mes_en_rol', models.IntegerField(verbose_name='Mes en Rol')),
                ('meta_datos_opc', models.IntegerField(default=0, verbose_name='Meta Datos OPC')),
                ('meta_presencias', models.IntegerField(default=0, verbose_name='Meta Presencias')),
                ('meta_ventas_directas', models.IntegerField(default=0, verbose_name='Meta Ventas Directas')),
                ('meta_juniors_captados', models.IntegerField(default=0, verbose_name='Meta Juniors Captados')),
                ('meta_ventas_equipo_socio', models.IntegerField(default=0, verbose_name='Meta Ventas Equipo (Socio)')),
                ('meta_cierres_socio_equipo', models.IntegerField(default=0, verbose_name='Meta Cierres Socio (Ventas Equipo)')),
                ('comision_residual_venta_equipo_porc', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Comisión Residual por Venta Equipo (%)')),
            ],
            options={
                'verbose_name': 'Definición de Meta y Comisión',
                'verbose_name_plural': 'Definiciones de Metas y Comisiones',
                'ordering': ['tipo_asesor', 'mes_en_rol'],
                'unique_together': {('tipo_asesor', 'mes_en_rol')},
            },
        ),
        migrations.CreateModel(
            name='TablaComisionDirecta',
            fields=[
                ('id_tabla_comision', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(choices=[('credito', 'Crédito'), ('contado', 'Contado')], max_length=10, verbose_name='Tipo de Venta')),
                ('mes_junior_venta', models.IntegerField(verbose_name='Mes del Junior en la Venta')),
                ('participacion_junior_venta', models.CharField(choices=[('opc y call', 'OPC y Call'), ('opc, call y línea', 'OPC, Call y Línea'), ('opc, call, front', 'OPC, Call, Front'), ('N/A', 'No Aplica')], max_length=50, verbose_name='Participación del Junior')),
                ('comision_junior_porc', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Comisión Junior (%)')),
                ('comision_socio_participante_porc', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Comisión Socio Participante (%)')),
            ],
            options={
                'verbose_name': 'Tabla de Comisión Directa',
                'verbose_name_plural': 'Tablas de Comisiones Directas',
                'ordering': ['tipo_venta', 'mes_junior_venta'],
                'unique_together': {('tipo_venta', 'mes_junior_venta', 'participacion_junior_venta')},
            },
        ),

        migrations.CreateModel(
            name='ActividadDiaria',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actividad', models.DateField(verbose_name='Fecha de Actividad')),
                ('datos_captados_opc', models.IntegerField(default=0, verbose_name='Datos Captados OPC')),
                ('llamadas_realizadas', models.IntegerField(default=0, verbose_name='Llamadas Realizadas')),
                ('presencias_generadas', models.IntegerField(default=0, verbose_name='Presencias Generadas')),
                ('notas_actividad', models.TextField(blank=True, null=True, verbose_name='Notas de Actividad')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestion_inmobiliaria.asesor', verbose_name='Asesor')),
            ],
            options={
                'verbose_name': 'Actividad Diaria',
                'verbose_name_plural': 'Actividades Diarias',
                'ordering': ['-fecha_actividad', 'asesor'],
                'unique_together': {('fecha_actividad', 'asesor')},
            },
        ),
    ]
