# jcc_inmobiliaria_backend/gestion_inmobiliaria/migrations/0002_add_venta_model.py
# Generated by Django 5.2.1 on YYYY-MM-DD HH:MM (puedes ajustar la fecha/hora o dejarla así)
# Este archivo es creado manualmente para el modelo Venta.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0001_initial'), # MUY IMPORTANTE: Depende de la migración anterior
    ]

    operations = [
        migrations.CreateModel( # ESTE ES EL BLOQUE QUE PEGaste
            name='Venta',
            fields=[
                ('id_venta', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Venta')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de Venta')),
                ('valor_lote_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Venta (S/.)')),
                ('tipo_venta', models.CharField(choices=[('credito', 'Crédito'), ('contado', 'Contado')], max_length=10, verbose_name='Tipo de Venta')),
                ('participacion_junior_venta', models.CharField(blank=True, choices=[('opc y call', 'OPC y Call'), ('opc, call y línea', 'OPC, Call y Línea'), ('opc, call, front', 'OPC, Call, Front'), ('N/A', 'No Aplica')], max_length=50, null=True, verbose_name='Participación Junior')),
                ('participacion_socio_venta', models.CharField(blank=True, choices=[('front', 'Front'), ('cierre', 'Cierre'), ('no participa', 'No Participa'), ('N/A', 'No Aplica')], max_length=20, null=True, verbose_name='Participación Socio')),
                ('modalidad_presentacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidad Presentación')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_registro_venta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cliente', to='gestion_inmobiliaria.cliente', verbose_name='Cliente')),
                ('id_socio_participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_socio', to='gestion_inmobiliaria.asesor', verbose_name='ID Socio Participante')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_lote', to='gestion_inmobiliaria.lote', verbose_name='Lote Vendido')),
                ('vendedor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='gestion_inmobiliaria.asesor', verbose_name='Vendedor Principal')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]