# Generated by Django 5.2.1 on 2025-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0002_add_venta_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='etapa',
            field=models.CharField(blank=True, choices=[('preventa', 'Preventa'), ('construccion', 'En Construcción'), ('entrega_inmediata', 'Entrega Inmediata'), ('otro', 'Otro')], default='preventa', max_length=30, null=True, verbose_name='Etapa del Lote'),
        ),
    ]
