# Generated by Django 5.2.1 on 2025-07-01 20:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0002_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionVentaAsesor',
            fields=[
                ('id_comision_venta_asesor', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('captacion_opc', 'Captación OPC/Redes'), ('call', 'Call (Agendó)'), ('liner', 'Liner (Presentación)'), ('closer', 'Closer (Cierre)'), ('otro', 'Otro')], max_length=20, verbose_name='Rol del Asesor en la Venta')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje de Comisión Asignado (%)')),
                ('monto_comision_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Comisión Calculado (S/.)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_en_ventas', to='gestion_inmobiliaria.asesor', verbose_name='Asesor Involucrado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_asesores', to='gestion_inmobiliaria.venta', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Comisión de Venta por Asesor',
                'verbose_name_plural': 'Comisiones de Ventas por Asesor',
                'ordering': ['venta', 'asesor'],
                'unique_together': {('venta', 'asesor', 'rol')},
            },
        ),
    ]
