# Generated by Django 5.2.1 on 2025-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0003_lote_etapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['ubicacion_proyecto', 'etapa', 'manzana', 'numero_lote'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterField(
            model_name='lote',
            name='etapa',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de la etapa del lote dentro del proyecto (ej: 1, 2, 3)', null=True, verbose_name='Etapa del Lote (Número)'),
        ),
    ]
