# Generated by Django 5.2.1 on 2025-07-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0003_comisionventaasesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='gestion_inmobiliaria.asesor', verbose_name='Vendedor Principal'),
        ),
    ]
