# Generated by Django 5.2.1 on 2025-07-03 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0004_alter_venta_vendedor_principal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gestion', models.DateTimeField(auto_now_add=True)),
                ('tipo_contacto', models.CharField(choices=[('LLAMADA', 'Llamada Telefónica'), ('WHATSAPP', 'Mensaje de WhatsApp'), ('EMAIL', 'Correo Electrónico'), ('CARTA', 'Carta Notarial')], max_length=10)),
                ('resultado', models.TextField(help_text='Ej: Cliente confirma pago para el día de mañana.')),
                ('proximo_seguimiento', models.DateField(blank=True, null=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_cobranza', to='gestion_inmobiliaria.cuotaplanpago')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
