# Generated by Django 5.2.1 on 2025-05-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0004_alter_lote_options_alter_lote_etapa'),
        ('gestion_inmobiliaria', '0005_convertir_etapa_a_numero'),
    ]

    operations = [
    ]
