# Generated by Django 5.2.1 on 2025-07-03 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0005_gestioncobranza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreComisionMensual',
            fields=[
                ('id_cierre', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('PAGADO', 'Pagado')], default='ABIERTO', max_length=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora en que se ejecutó el cierre.', null=True)),
                ('monto_total_comisiones', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Comisión Mensual',
                'verbose_name_plural': 'Cierres de Comisiones Mensuales',
                'ordering': ['-año', '-mes'],
                'unique_together': {('mes', 'año')},
            },
        ),
        migrations.CreateModel(
            name='DetalleComisionCerrada',
            fields=[
                ('id_detalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asesor_nombre', models.CharField(max_length=255)),
                ('asesor_dni', models.CharField(max_length=20)),
                ('venta_id', models.CharField(max_length=20)),
                ('lote_str', models.CharField(max_length=255)),
                ('fecha_venta', models.DateField()),
                ('rol_en_venta', models.CharField(max_length=100)),
                ('monto_base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_comision_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_comision_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_inmobiliaria.cierrecomisionmensual')),
                ('comision_original', models.OneToOneField(help_text='Referencia a la comisión original', on_delete=django.db.models.deletion.PROTECT, to='gestion_inmobiliaria.comisionventaasesor')),
            ],
            options={
                'verbose_name': 'Detalle de Comisión Cerrada',
                'verbose_name_plural': 'Detalles de Comisiones Cerradas',
                'ordering': ['asesor_nombre', 'fecha_venta'],
            },
        ),
    ]
