# Generated by Django 5.2.1 on 2025-05-22 21:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0006_merge_20250522_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuota_inicial_requerida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cuota Inicial Requerida (S/.)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pagado_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Pagado Actual (S/.)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='status_venta',
            field=models.CharField(choices=[('separacion', 'Separación'), ('procesable', 'Procesable'), ('anulado', 'Anulado')], default='separacion', max_length=20, verbose_name='Status de la Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='valor_lote_venta',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Venta Total (S/.)'),
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Pago')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del Pago (S/.)')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('yape_plin', 'Yape/Plin'), ('otro', 'Otro')], max_length=30, null=True, verbose_name='Método de Pago')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia (N° Op, Código, etc.)')),
                ('notas_pago', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales del Pago')),
                ('fecha_registro_pago', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pago', to='gestion_inmobiliaria.venta', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
