# Generated by Django 5.2.1 on 2025-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0007_venta_cuota_inicial_requerida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablacomisiondirecta',
            options={'ordering': ['rol_asesor_en_venta', 'tipo_venta'], 'verbose_name': 'Tabla de Comisión Directa', 'verbose_name_plural': 'Tablas de Comisiones Directas'},
        ),
        migrations.AlterUniqueTogether(
            name='tablacomisiondirecta',
            unique_together={('rol_asesor_en_venta', 'tipo_venta', 'participacion_en_venta_aplicable')},
        ),
        migrations.AddField(
            model_name='tablacomisiondirecta',
            name='participacion_en_venta_aplicable',
            field=models.CharField(choices=[('opc y call', 'OPC y Call'), ('opc, call y línea', 'OPC, Call y Línea'), ('opc, call, front', 'OPC, Call, Front'), ('N/A', 'No Aplica'), ('front', 'Front'), ('cierre', 'Cierre'), ('no participa', 'No Participa')], default='N/A', help_text="Ej: 'opc y call' (Junior), 'front' (Socio Part.), 'N/A' (Socio VP)", max_length=50, verbose_name='Participación Aplicable para esta regla'),
        ),
        migrations.AddField(
            model_name='tablacomisiondirecta',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Porcentaje de Comisión (%)'),
        ),
        migrations.AddField(
            model_name='tablacomisiondirecta',
            name='rol_asesor_en_venta',
            field=models.CharField(choices=[('JUNIOR_VENDEDOR_PRINCIPAL', 'Junior como Vendedor Principal'), ('SOCIO_VENDEDOR_PRINCIPAL', 'Socio como Vendedor Principal'), ('SOCIO_PARTICIPANTE', 'Socio como Participante en venta de Junior')], default='JUNIOR_VENDEDOR_PRINCIPAL', max_length=50, verbose_name='Rol del Asesor en la Venta para esta comisión'),
        ),
        migrations.RemoveField(
            model_name='tablacomisiondirecta',
            name='comision_junior_porc',
        ),
        migrations.RemoveField(
            model_name='tablacomisiondirecta',
            name='comision_socio_participante_porc',
        ),
        migrations.RemoveField(
            model_name='tablacomisiondirecta',
            name='mes_junior_venta',
        ),
        migrations.RemoveField(
            model_name='tablacomisiondirecta',
            name='participacion_junior_venta',
        ),
    ]
