# Generated by Django 5.2.1 on 2025-05-23 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0008_alter_tablacomisiondirecta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presencia',
            fields=[
                ('id_presencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_presencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de la Presencia/Cita')),
                ('proyecto_interes', models.CharField(max_length=255, verbose_name='Proyecto de Interés')),
                ('medio_captacion', models.CharField(choices=[('campo_opc', 'Campo OPC'), ('redes_facebook', 'Redes Facebook'), ('redes_instagram', 'Redes Instagram'), ('redes_tiktok', 'Redes TikTok'), ('referido', 'Referido'), ('web', 'Página Web'), ('otro', 'Otro')], max_length=50, verbose_name='Medio de Captación')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20, verbose_name='Modalidad de la Presencia')),
                ('status_presencia', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('reprogramada', 'Reprogramada'), ('cancelada_cliente', 'Cancelada por Cliente'), ('no_asistio', 'No Asistió'), ('caida_proceso', 'Caída en Proceso')], default='agendada', max_length=30, verbose_name='Estado de la Presencia/Cita')),
                ('resultado_interaccion', models.CharField(blank=True, choices=[('interesado_seguimiento', 'Interesado - Programar Seguimiento'), ('interesado_separacion', 'Interesado - Realizó Separación'), ('interesado_venta_directa', 'Interesado - Venta Directa'), ('no_interesado_objecion', 'No Interesado - Objeción'), ('no_interesado_precio', 'No Interesado - Precio'), ('no_interesado_otro', 'No Interesado - Otro')], max_length=50, null=True, verbose_name='Resultado Específico de la Interacción')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro_sistema', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('asesor_call_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_agendadas_call', to='gestion_inmobiliaria.asesor', verbose_name='Asesor Call que Agendó')),
                ('asesor_captacion_opc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_captadas_opc', to='gestion_inmobiliaria.asesor', verbose_name='Asesor Captación OPC/Redes')),
                ('asesor_closer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_como_closer', to='gestion_inmobiliaria.asesor', verbose_name='Asesor Closer (Cierre)')),
                ('asesor_liner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_como_liner', to='gestion_inmobiliaria.asesor', verbose_name='Asesor Liner (Presentación)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencias_cliente', to='gestion_inmobiliaria.cliente', verbose_name='Cliente')),
                ('lote_interes_inicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_interes_en_lote', to='gestion_inmobiliaria.lote', verbose_name='Lote de Interés Inicial')),
                ('venta_asociada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencia_que_origino', to='gestion_inmobiliaria.venta', verbose_name='Venta Asociada (si aplica)')),
            ],
            options={
                'verbose_name': 'Presencia de Cliente',
                'verbose_name_plural': 'Presencias de Clientes',
                'ordering': ['-fecha_hora_presencia'],
            },
        ),
    ]
