# Generated by Django 5.2.1 on 2025-05-23 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0009_presencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividaddiaria',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_diarias_asesor', to='gestion_inmobiliaria.asesor', verbose_name='Asesor'),
        ),
    ]
