# Generated by Django 5.2.1 on 2025-05-26 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0010_alter_actividaddiaria_asesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='banco_preferido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco Preferido'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='cci_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CCI Cuenta Bancaria'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='direccion_domicilio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Domicilio'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Personal'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Conviviente', 'Conviviente')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='fecha_registro_sistema',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Registro en Sistema'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='numero_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta Bancaria'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='numero_hijos',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Número de Hijos'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='observaciones_asesor',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='telefono_personal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Personal'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='ultima_modificacion_sistema',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación en Sistema'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='fecha_cambio_socio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cambio a Socio (si aplica)'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso a la Empresa'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='id_referidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='gestion_inmobiliaria.asesor', verbose_name='ID Referidor (Líder)'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='nombre_asesor',
            field=models.CharField(max_length=255, verbose_name='Nombre Completo del Asesor'),
        ),
    ]
