# Generated by Django 5.2.1 on 2025-05-26 20:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0011_asesor_banco_preferido_asesor_cci_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='porcentaje_comision_socio_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dejar en blanco para usar tabla de comisiones. Aplicable si hay socio participante. Ingresar valor entre 0.00 y 100.00.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Comisión Personalizada Socio Participante (%)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='porcentaje_comision_vendedor_principal_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dejar en blanco para usar tabla de comisiones. Ingresar valor entre 0.00 y 100.00.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Comisión Personalizada Vendedor Principal (%)'),
        ),
        migrations.AlterField(
            model_name='actividaddiaria',
            name='llamadas_realizadas',
            field=models.IntegerField(default=0, verbose_name='Datos Gestionados'),
        ),
    ]
