# Generated by Django 5.2.1 on 2025-05-26 22:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0012_venta_porcentaje_comision_socio_personalizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaPlanPago',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.PositiveSmallIntegerField(verbose_name='Número de Cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto_programado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Programado de Cuota')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Pagado')),
                ('estado_cuota', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('parcialmente_pagada', 'Parcialmente Pagada'), ('atrasada', 'Atrasada'), ('vencida_no_pagada', 'Vencida No Pagada')], default='pendiente', max_length=25, verbose_name='Estado de la Cuota')),
                ('fecha_pago_efectivo', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Efectivo')),
            ],
            options={
                'verbose_name': 'Cuota de Plan de Pago',
                'verbose_name_plural': 'Cuotas de Planes de Pago',
                'ordering': ['plan_pago_venta', 'numero_cuota'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='precio_credito_12_meses_soles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Crédito 12 Meses (S/.)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='precio_credito_24_meses_soles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Crédito 24 Meses (S/.)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='precio_credito_36_meses_soles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Crédito 36 Meses (S/.)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='plazo_meses_credito',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Contado'), (12, 'Crédito 12 Meses'), (24, 'Crédito 24 Meses'), (36, 'Crédito 36 Meses')], help_text='Seleccionar solo si el tipo de venta es a Crédito.', null=True, verbose_name='Plazo de Crédito (Meses)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_lista_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Lista ($) (Opcional)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_lista_soles',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Contado (S/.)'),
        ),
        migrations.AlterField(
            model_name='tablacomisiondirecta',
            name='tipo_venta',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], max_length=10, verbose_name='Tipo de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Tipo de Venta'),
        ),
        migrations.AddField(
            model_name='registropago',
            name='cuota_plan_pago_cubierta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_que_la_cubren', to='gestion_inmobiliaria.cuotaplanpago', verbose_name='Cuota del Plan Cubierta (Opcional)'),
        ),
        migrations.CreateModel(
            name='PlanPagoVenta',
            fields=[
                ('id_plan_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total_credito', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total del Crédito')),
                ('numero_cuotas', models.PositiveSmallIntegerField(verbose_name='Número de Cuotas')),
                ('monto_cuota_regular', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Cuota Regular')),
                ('fecha_inicio_pago_cuotas', models.DateField(verbose_name='Fecha de Inicio de Pago de Cuotas')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pago_venta', to='gestion_inmobiliaria.venta', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Plan de Pago de Venta',
                'verbose_name_plural': 'Planes de Pago de Ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='cuotaplanpago',
            name='plan_pago_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='gestion_inmobiliaria.planpagoventa', verbose_name='Plan de Pago Asociado'),
        ),
        migrations.AlterUniqueTogether(
            name='cuotaplanpago',
            unique_together={('plan_pago_venta', 'numero_cuota')},
        ),
    ]
