# Generated by Django 5.2.1 on 2025-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0013_cuotaplanpago_lote_precio_credito_12_meses_soles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotaplanpago',
            name='estado_cuota',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('parcialmente_pagada', 'Parcialmente Pagada'), ('atrasada', 'Atrasada'), ('vencida_no_pagada', 'Vencida No Pagada'), ('cancelada_con_excedente', 'Cancelada con Excedente')], default='pendiente', max_length=25, verbose_name='Estado de la Cuota'),
        ),
        migrations.AlterField(
            model_name='cuotaplanpago',
            name='fecha_pago_efectivo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Último Pago/Pago Completo'),
        ),
        migrations.AlterField(
            model_name='planpagoventa',
            name='fecha_inicio_pago_cuotas',
            field=models.DateField(verbose_name='Fecha de Vencimiento de Primera Cuota'),
        ),
        migrations.AlterField(
            model_name='planpagoventa',
            name='monto_total_credito',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total del Crédito (Post Cuota Inicial)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='plazo_meses_credito',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Contado / Sin Plan'), (12, 'Crédito 12 Meses'), (24, 'Crédito 24 Meses'), (36, 'Crédito 36 Meses')], default=0, help_text='0 para Contado. Seleccionar plazo si el tipo de venta es Crédito.', verbose_name='Plazo de Crédito (Meses)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='status_venta',
            field=models.CharField(choices=[('separacion', 'Separación'), ('procesable', 'Procesable'), ('completada', 'Completada'), ('anulado', 'Anulado')], default='separacion', max_length=20, verbose_name='Status de la Venta'),
        ),
    ]
