# Generated by Django 5.2.1 on 2025-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0014_alter_cuotaplanpago_estado_cuota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpagoventa',
            name='monto_cuota_regular',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Cuota Regular Original'),
        ),
    ]
