# Generated by Django 5.2.1 on 2025-05-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0015_alter_planpagoventa_monto_cuota_regular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planpagoventa',
            old_name='monto_cuota_regular',
            new_name='monto_cuota_regular_original',
        ),
    ]
