# Generated by Django 5.2.1 on 2025-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0016_rename_monto_cuota_regular_planpagoventa_monto_cuota_regular_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_firmo_contrato',
            field=models.BooleanField(default=False, verbose_name='¿Cliente Firmó Contrato?'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_firma_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Firma de Contrato'),
        ),
    ]
