# Generated by Django 5.2.1 on 2025-05-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0017_venta_cliente_firmo_contrato_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actividaddiaria',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='actividaddiaria',
            name='id_actividad',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Actividad'),
        ),
        migrations.AlterField(
            model_name='presencia',
            name='id_presencia',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Presencia'),
        ),
        migrations.AlterField(
            model_name='registropago',
            name='id_pago',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Pago'),
        ),
    ]
