# Generated by Django 5.2.1 on 2025-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0018_alter_actividaddiaria_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesor',
            name='direccion_domicilio',
        ),
        migrations.AddField(
            model_name='asesor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección del Asesor'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito del Asesor'),
        ),
    ]
