# Generated by Django 5.2.1 on 2025-05-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0019_remove_asesor_direccion_domicilio_asesor_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='banco',
            field=models.CharField(blank=True, choices=[('BCP', 'Banco de Crédito BCP'), ('Interbank', 'Interbank'), ('Scotiabank', 'Scotiabank'), ('BBVA', 'BBVA Continental'), ('Otro', 'Otro Banco (especificar en notas)')], max_length=50, null=True, verbose_name='Banco Principal'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='cuenta_bancaria_otros',
            field=models.TextField(blank=True, null=True, verbose_name='Otras Cuentas o Detalles Bancarios Adicionales'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='cci_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CCI Cuenta Bancaria Principal'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='numero_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta Bancaria Principal'),
        ),
    ]
