# Generated by Django 5.2.1 on 2025-06-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0020_asesor_banco_asesor_cuenta_bancaria_otros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencia',
            name='tipo_tour',
            field=models.CharField(choices=[('tour', 'Tour (Presencia Real)'), ('no_tour', 'No Tour (Cita Confirmada, No Presencia)')], default='tour', help_text='Indica si la cita fue un Tour (presencia real) o No Tour (no califica como presencia)', max_length=10, verbose_name='Tipo de Presencia (Tour/No Tour)'),
        ),
    ]
