# Generated by Django 5.2.1 on 2025-06-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0023_lote_precios_credito_dolares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='precio_lista_soles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Contado (S/.)'),
        ),
    ]
