# Generated by Django 5.2.1 on 2025-06-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria', '0024_alter_lote_precio_lista_soles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaplanpago',
            name='monto_programado_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Programado de Cuota ($)'),
        ),
        migrations.AddField(
            model_name='registropago',
            name='monto_pago_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto del Pago ($)'),
        ),
        migrations.AddField(
            model_name='registropago',
            name='monto_pago_soles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto del Pago (S/.) calculado'),
        ),
        migrations.AddField(
            model_name='registropago',
            name='tipo_cambio_pago',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Tipo de Cambio del Pago (S/ por $)'),
        ),
    ]
