"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Importado por si se usa para variables de entorno más adelante

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-i=bfp%_6)*egr-0jc5uq-i9uvng(nidj6p)ma0_03@+(3t7mkw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Correcto para desarrollo

# Con DEBUG=True, ALLOWED_HOSTS por defecto permite ['localhost', '127.0.0.1', '[::1]']
# Para desarrollo local, esto está bien. Para producción, debes especificar tus hosts.
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions', # Necesario para SessionAuthentication
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',             # Para manejar CORS
    'rest_framework',
    'django_filters',          # Django REST framework
    'gestion_inmobiliaria',    # Tu aplicación principal
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Debe estar antes de la mayoría de los otros middlewares, especialmente CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # Necesario para SessionAuthentication
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Esencial para la protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Necesario para request.user
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# El orden del MIDDLEWARE parece correcto.

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'jccinmobiliaria_db',
        'USER': 'jorge',
        'PASSWORD': 'jorge123', # Considera usar variables de entorno también para esto
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
LANGUAGE_CODE = 'es-pe'
TIME_ZONE = 'America/Lima'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
# -----------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:8000", # Correcto, permite el acceso desde 127.0.0.1
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:8000", # Correcto, confía en peticiones de 127.0.0.1
]
CSRF_COOKIE_HTTPONLY = False # Correct

# Por defecto, CSRF_COOKIE_SECURE es False, lo cual es correcto para desarrollo en HTTP.
# Si estuvieras en HTTPS, debería ser True.
# CSRF_COOKIE_SECURE = False (valor por defecto)

# Por defecto, CSRF_COOKIE_PATH es '/', lo cual es correcto.
# CSRF_COOKIE_PATH = '/' (valor por defecto)

# Por defecto, CSRF_COOKIE_DOMAIN es None, lo que significa que la cookie se establece para el dominio actual.
# Esto está bien para desarrollo si frontend y backend están en 'localhost' o '127.0.0.1'.
# CSRF_COOKIE_DOMAIN = None (valor por defecto)


# Django REST framework settings
# -----------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Valor por defecto, el frontend podrá cambiarlo con ?page_size=10|20|50|100
}

# --- CONFIGURACIÓN DE INTEGRACIÓN CON CRM ---
# Token de autenticación para recibir webhooks del CRM (debe coincidir con COMERCIAL_WEBHOOK_TOKEN en el CRM)
CRM_WEBHOOK_TOKEN = os.environ.get('CRM_WEBHOOK_TOKEN', 'jcc-webhook-secret-token-2024')